// Fetch News Actions
export const FETCH_TOP_NEWS_PENDING = 'FETCH_TOP_NEWS_PENDING';
export const FETCH_TOP_NEWS_SUCCESS = 'FETCH_TOP_NEWS_SUCCESS';
export const FETCH_TOP_NEWS_ERROR = 'FETCH_TOP_NEWS_ERROR';

// Fetch Headlines Actions

export const FETCH_HEADLINES_PENDING = 'FETCH_HEADLINES_PENDING';
export const FETCH_HEADLINES_SUCCESS = 'FETCH_HEADLINES_SUCCESS';
export const FETCH_HEADLINES_ERROR = 'FETCH_HEADLINES_ERROR';
