// Fetch News Actions
export const FETCH_TOP_NEWS_PENDING = 'FETCH_TOP_NEWS_PENDING';
export const FETCH_TOP_NEWS_SUCCESS = 'FETCH_TOP_NEWS_SUCCESS';
export const FETCH_TOP_NEWS_ERROR = 'FETCH_TOP_NEWS_ERROR';
